apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "busybox-app.fullname" . }}
  labels:
    app: {{ include "busybox-app.name" . }}
    chart: {{ include "busybox-app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "busybox-app.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "busybox-app.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: busybox
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: {{ .Values.command }}
          args: {{ .Values.args }}
          resources: {{ toYaml .Values.resources | nindent 12 }}
      nodeSelector: {{ toYaml .Values.nodeSelector | nindent 8 }}
      tolerations: {{ toYaml .Values.tolerations | nindent 8 }}
      affinity: {{ toYaml .Values.affinity | nindent 8 }}
